Controllers/ProductLineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OrdersAssessment.Models;
using OrdersAssessment.ViewModel;
using PagedList;
using PagedList.Mvc;

namespace OrdersAssessment.Controllers
{
    public class ProductLineController : Controller
    {

        

        // GET: ProductLine
        public ActionResult Index(int? page)
        {
            if (Session["user_id"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            ProductLines productLine = new ProductLines();
            productLine.createdBy = (int)Session["user_id"];
            var viewModel = new ViewModel.ViewModel
            {
                ProductLines = productLine.getAllProductLines(null).ToList().ToPagedList(page ?? 1,3)
            };
            return View(viewModel);
        }

        //Add product line
        [HttpPost]
        public ActionResult AddProductLine()
        {
            if (Session["user_id"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            if (Request["product_line"] != null)
            {
                ProductLines productLine = new ProductLines();
                productLine.product_line_name = Request["product_line"].ToString();
                productLine.createdBy = (int)Session["user_id"];
                if(productLine.hasCreatedProductLine())
                {
                    //created_product_line
                    return RedirectToAction("Index", new { @status = "success", @message = "Product Line successfully created" });
                }
            }
            else
            {
                return RedirectToAction("Index", new { @status = "danger", @message = "Error failed adding new product line" });
            }

            return RedirectToAction("Index", new { @status = "danger", @message = "Error failed adding new product line" });

        }

        public ActionResult Edit(int? Id)
        {
            if (Session["user_id"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            if (Id.Equals(null))
            {
                return RedirectToAction("Index");
            }

            ProductLines productLine = new ProductLines();
            productLine.Id = (int)Id;
            productLine.createdBy = (int)Session["user_id"];
            var viewModel = new ViewModel.ViewModel
            {
                AllProductLinesList = productLine.getAllProductLines(Id)
            };
            if (viewModel.AllProductLinesList.Count == 0)
            {
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        //Edit Product line
        [HttpPost]
        public ActionResult UpdateProductLine(int Id)
        {
            if (Session["user_id"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            if (Id.Equals(null))
            {
                return RedirectToAction("Index");
            }
            var result = false;
            if (Request["product_line"] != null)
            {
                ProductLines productLine = new ProductLines();
                productLine.product_line_name = Request["product_line"].ToString();
                productLine.createdBy = (int)Session["user_id"];
                productLine.Id = Id;
                if (productLine.hasUpdatedProductLine())
                {

                }
            }
            else
            {
                result = false;
            }

            return RedirectToAction("Index");
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OrdersAssessment.Models;

namespace OrdersAssessment.Controllers
{
    public class UsersController : Controller
    {        
            // Login Page
            public ActionResult Login()
            {                
                return View();
            }

            //Login Post
            [HttpPost]
            public ActionResult LoginUser()
            {
                Users usersModel = new Users();
                usersModel.username = Request["username"];
                usersModel.password = Request["password"];
                var user_id = usersModel.isValidUser();
                    if (user_id > 0)
                    {
                        Session["user_id"] = user_id;
                        return RedirectToAction("Index", "Orders");
                    }
                    else
                    {
                        return RedirectToAction("Login", new { @status = "danger", @message = "Please make sure you are using the correct username or password" });                
                    }
            }

            //Logout
            public ActionResult LogoutUser()
            {
                Session.Clear();
                Session.Abandon();                
                return RedirectToAction("Login");
            }        
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
  
</head>
<body>

    @Html.Partial("_Navbar")

    
    <div class="container body-content">
        @if (Request["status"] != null)
        {
            var alertClass = Request["status"] == "success" ? "alert alert-success" : "alert alert-danger";
            <div class="@alertClass">
                @Request["message"]
            </div>
        }      
        @RenderBody()
    </div>

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            if($("alert").length != null)
            {
                setTimeout(function () {
                    $(".alert").fadeOut();
                }, 3000);
            }
        });
    </script>
</body>
</html>

Views/Shared/_Navbar.cshtml
@inherits System.Web.Mvc.WebViewPage
<div class="navbar navbar-fixed-top primary_background_color mb-3">
    <div class="container">
        <div class="navbar-header text-center">
            <img class="text-center" width="130px" src="~/Images/logodesktop.png" />
        </div>
        <div class="row">
            <div class="col-lg-12 text-white">
                @Html.ActionLink("Orders", "Index", "Orders", null, new { @class = "text-white" }) |
                @Html.ActionLink("Suppliers", "Index", "Suppliers", null, new { @class = "text-white" }) |
                @Html.ActionLink("Product Lines", "Index", "ProductLine", null, new { @class = "text-white" }) |
                @Html.ActionLink("Logout", "LogoutUser", "Users", null, new { @class = "text-white" })
            </div>
        </div>
    </div>
</div>